// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: prompt/prompt_service.proto

package prompt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ModelId       string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromptRequest) Reset() {
	*x = CreatePromptRequest{}
	mi := &file_prompt_prompt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromptRequest) ProtoMessage() {}

func (x *CreatePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromptRequest.ProtoReflect.Descriptor instead.
func (*CreatePromptRequest) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePromptRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CreatePromptRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePromptRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CreatePromptRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreatePromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *Prompt                `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromptResponse) Reset() {
	*x = CreatePromptResponse{}
	mi := &file_prompt_prompt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromptResponse) ProtoMessage() {}

func (x *CreatePromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromptResponse.ProtoReflect.Descriptor instead.
func (*CreatePromptResponse) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePromptResponse) GetPrompt() *Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

type GetPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptRequest) Reset() {
	*x = GetPromptRequest{}
	mi := &file_prompt_prompt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptRequest) ProtoMessage() {}

func (x *GetPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptRequest.ProtoReflect.Descriptor instead.
func (*GetPromptRequest) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPromptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *Prompt                `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptResponse) Reset() {
	*x = GetPromptResponse{}
	mi := &file_prompt_prompt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptResponse) ProtoMessage() {}

func (x *GetPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptResponse.ProtoReflect.Descriptor instead.
func (*GetPromptResponse) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPromptResponse) GetPrompt() *Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

type ListPromptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsRequest) Reset() {
	*x = ListPromptsRequest{}
	mi := &file_prompt_prompt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsRequest) ProtoMessage() {}

func (x *ListPromptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsRequest.ProtoReflect.Descriptor instead.
func (*ListPromptsRequest) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListPromptsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListPromptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompts       []*Prompt              `protobuf:"bytes,1,rep,name=prompts,proto3" json:"prompts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsResponse) Reset() {
	*x = ListPromptsResponse{}
	mi := &file_prompt_prompt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsResponse) ProtoMessage() {}

func (x *ListPromptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsResponse.ProtoReflect.Descriptor instead.
func (*ListPromptsResponse) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListPromptsResponse) GetPrompts() []*Prompt {
	if x != nil {
		return x.Prompts
	}
	return nil
}

type UpdatePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ModelId       string                 `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromptRequest) Reset() {
	*x = UpdatePromptRequest{}
	mi := &file_prompt_prompt_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromptRequest) ProtoMessage() {}

func (x *UpdatePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromptRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromptRequest) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePromptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePromptRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *UpdatePromptRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePromptRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *UpdatePromptRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type UpdatePromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *Prompt                `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromptResponse) Reset() {
	*x = UpdatePromptResponse{}
	mi := &file_prompt_prompt_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromptResponse) ProtoMessage() {}

func (x *UpdatePromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromptResponse.ProtoReflect.Descriptor instead.
func (*UpdatePromptResponse) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePromptResponse) GetPrompt() *Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

type DeletePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromptRequest) Reset() {
	*x = DeletePromptRequest{}
	mi := &file_prompt_prompt_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromptRequest) ProtoMessage() {}

func (x *DeletePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromptRequest.ProtoReflect.Descriptor instead.
func (*DeletePromptRequest) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePromptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromptResponse) Reset() {
	*x = DeletePromptResponse{}
	mi := &file_prompt_prompt_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromptResponse) ProtoMessage() {}

func (x *DeletePromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromptResponse.ProtoReflect.Descriptor instead.
func (*DeletePromptResponse) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePromptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_prompt_prompt_service_proto protoreflect.FileDescriptor

const file_prompt_prompt_service_proto_rawDesc = "" +
	"\n" +
	"\x1bprompt/prompt_service.proto\x12\x06prompt\x1a\x13prompt/prompt.proto\"\xa3\x01\n" +
	"\x13CreatePromptRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\">\n" +
	"\x14CreatePromptResponse\x12&\n" +
	"\x06prompt\x18\x01 \x01(\v2\x0e.prompt.PromptR\x06prompt\"\"\n" +
	"\x10GetPromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetPromptResponse\x12&\n" +
	"\x06prompt\x18\x01 \x01(\v2\x0e.prompt.PromptR\x06prompt\"5\n" +
	"\x12ListPromptsRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\"?\n" +
	"\x13ListPromptsResponse\x12(\n" +
	"\aprompts\x18\x01 \x03(\v2\x0e.prompt.PromptR\aprompts\"\xb3\x01\n" +
	"\x13UpdatePromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\tR\amodelId\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\">\n" +
	"\x14UpdatePromptResponse\x12&\n" +
	"\x06prompt\x18\x01 \x01(\v2\x0e.prompt.PromptR\x06prompt\"%\n" +
	"\x13DeletePromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeletePromptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfa\x02\n" +
	"\rPromptService\x12I\n" +
	"\fCreatePrompt\x12\x1b.prompt.CreatePromptRequest\x1a\x1c.prompt.CreatePromptResponse\x12@\n" +
	"\tGetPrompt\x12\x18.prompt.GetPromptRequest\x1a\x19.prompt.GetPromptResponse\x12F\n" +
	"\vListPrompts\x12\x1a.prompt.ListPromptsRequest\x1a\x1b.prompt.ListPromptsResponse\x12I\n" +
	"\fUpdatePrompt\x12\x1b.prompt.UpdatePromptRequest\x1a\x1c.prompt.UpdatePromptResponse\x12I\n" +
	"\fDeletePrompt\x12\x1b.prompt.DeletePromptRequest\x1a\x1c.prompt.DeletePromptResponseB\x1bZ\x19portfolio-ai/proto/promptb\x06proto3"

var (
	file_prompt_prompt_service_proto_rawDescOnce sync.Once
	file_prompt_prompt_service_proto_rawDescData []byte
)

func file_prompt_prompt_service_proto_rawDescGZIP() []byte {
	file_prompt_prompt_service_proto_rawDescOnce.Do(func() {
		file_prompt_prompt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prompt_prompt_service_proto_rawDesc), len(file_prompt_prompt_service_proto_rawDesc)))
	})
	return file_prompt_prompt_service_proto_rawDescData
}

var file_prompt_prompt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_prompt_prompt_service_proto_goTypes = []any{
	(*CreatePromptRequest)(nil),  // 0: prompt.CreatePromptRequest
	(*CreatePromptResponse)(nil), // 1: prompt.CreatePromptResponse
	(*GetPromptRequest)(nil),     // 2: prompt.GetPromptRequest
	(*GetPromptResponse)(nil),    // 3: prompt.GetPromptResponse
	(*ListPromptsRequest)(nil),   // 4: prompt.ListPromptsRequest
	(*ListPromptsResponse)(nil),  // 5: prompt.ListPromptsResponse
	(*UpdatePromptRequest)(nil),  // 6: prompt.UpdatePromptRequest
	(*UpdatePromptResponse)(nil), // 7: prompt.UpdatePromptResponse
	(*DeletePromptRequest)(nil),  // 8: prompt.DeletePromptRequest
	(*DeletePromptResponse)(nil), // 9: prompt.DeletePromptResponse
	(*Prompt)(nil),               // 10: prompt.Prompt
}
var file_prompt_prompt_service_proto_depIdxs = []int32{
	10, // 0: prompt.CreatePromptResponse.prompt:type_name -> prompt.Prompt
	10, // 1: prompt.GetPromptResponse.prompt:type_name -> prompt.Prompt
	10, // 2: prompt.ListPromptsResponse.prompts:type_name -> prompt.Prompt
	10, // 3: prompt.UpdatePromptResponse.prompt:type_name -> prompt.Prompt
	0,  // 4: prompt.PromptService.CreatePrompt:input_type -> prompt.CreatePromptRequest
	2,  // 5: prompt.PromptService.GetPrompt:input_type -> prompt.GetPromptRequest
	4,  // 6: prompt.PromptService.ListPrompts:input_type -> prompt.ListPromptsRequest
	6,  // 7: prompt.PromptService.UpdatePrompt:input_type -> prompt.UpdatePromptRequest
	8,  // 8: prompt.PromptService.DeletePrompt:input_type -> prompt.DeletePromptRequest
	1,  // 9: prompt.PromptService.CreatePrompt:output_type -> prompt.CreatePromptResponse
	3,  // 10: prompt.PromptService.GetPrompt:output_type -> prompt.GetPromptResponse
	5,  // 11: prompt.PromptService.ListPrompts:output_type -> prompt.ListPromptsResponse
	7,  // 12: prompt.PromptService.UpdatePrompt:output_type -> prompt.UpdatePromptResponse
	9,  // 13: prompt.PromptService.DeletePrompt:output_type -> prompt.DeletePromptResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_prompt_prompt_service_proto_init() }
func file_prompt_prompt_service_proto_init() {
	if File_prompt_prompt_service_proto != nil {
		return
	}
	file_prompt_prompt_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prompt_prompt_service_proto_rawDesc), len(file_prompt_prompt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prompt_prompt_service_proto_goTypes,
		DependencyIndexes: file_prompt_prompt_service_proto_depIdxs,
		MessageInfos:      file_prompt_prompt_service_proto_msgTypes,
	}.Build()
	File_prompt_prompt_service_proto = out.File
	file_prompt_prompt_service_proto_goTypes = nil
	file_prompt_prompt_service_proto_depIdxs = nil
}
