// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: prompt/prompt.proto

package prompt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Prompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ModelId       string                 `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	mi := &file_prompt_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_prompt_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *Prompt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Prompt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prompt) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Prompt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Prompt) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *Prompt) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Prompt) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Prompt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_prompt_prompt_proto protoreflect.FileDescriptor

const file_prompt_prompt_proto_rawDesc = "" +
	"\n" +
	"\x13prompt/prompt.proto\x12\x06prompt\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\x06Prompt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\tR\amodelId\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x15Z\x13dan-ai/proto/promptb\x06proto3"

var (
	file_prompt_prompt_proto_rawDescOnce sync.Once
	file_prompt_prompt_proto_rawDescData []byte
)

func file_prompt_prompt_proto_rawDescGZIP() []byte {
	file_prompt_prompt_proto_rawDescOnce.Do(func() {
		file_prompt_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prompt_prompt_proto_rawDesc), len(file_prompt_prompt_proto_rawDesc)))
	})
	return file_prompt_prompt_proto_rawDescData
}

var file_prompt_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_prompt_prompt_proto_goTypes = []any{
	(*Prompt)(nil),                // 0: prompt.Prompt
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_prompt_prompt_proto_depIdxs = []int32{
	1, // 0: prompt.Prompt.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prompt_prompt_proto_init() }
func file_prompt_prompt_proto_init() {
	if File_prompt_prompt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prompt_prompt_proto_rawDesc), len(file_prompt_prompt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prompt_prompt_proto_goTypes,
		DependencyIndexes: file_prompt_prompt_proto_depIdxs,
		MessageInfos:      file_prompt_prompt_proto_msgTypes,
	}.Build()
	File_prompt_prompt_proto = out.File
	file_prompt_prompt_proto_goTypes = nil
	file_prompt_prompt_proto_depIdxs = nil
}
