// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/chat_service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorId     string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	PromptId      string                 `protobuf:"bytes,2,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *CreateSessionRequest) GetPromptId() string {
	if x != nil {
		return x.PromptId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ChatSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSession() *ChatSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorId     string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ChatSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*ChatSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type RenameSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionRequest) Reset() {
	*x = RenameSessionRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionRequest) ProtoMessage() {}

func (x *RenameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionRequest.ProtoReflect.Descriptor instead.
func (*RenameSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{4}
}

func (x *RenameSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RenameSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ChatSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionResponse) Reset() {
	*x = RenameSessionResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionResponse) ProtoMessage() {}

func (x *RenameSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionResponse.ProtoReflect.Descriptor instead.
func (*RenameSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{5}
}

func (x *RenameSessionResponse) GetSession() *ChatSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateMessageRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageResponse) Reset() {
	*x = CreateMessageResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageResponse) ProtoMessage() {}

func (x *CreateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VisitorId     string                 `protobuf:"bytes,2,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	PromptId      string                 `protobuf:"bytes,3,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMessageRequest) Reset() {
	*x = SendChatMessageRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageRequest) ProtoMessage() {}

func (x *SendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*SendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{14}
}

func (x *SendChatMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendChatMessageRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *SendChatMessageRequest) GetPromptId() string {
	if x != nil {
		return x.PromptId
	}
	return ""
}

func (x *SendChatMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RecentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentMessage) Reset() {
	*x = RecentMessage{}
	mi := &file_chat_chat_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentMessage) ProtoMessage() {}

func (x *RecentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentMessage.ProtoReflect.Descriptor instead.
func (*RecentMessage) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{15}
}

func (x *RecentMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RecentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RecentMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SendChatMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VisitorId      string                 `protobuf:"bytes,2,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RecentMessages []*RecentMessage       `protobuf:"bytes,4,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendChatMessageResponse) Reset() {
	*x = SendChatMessageResponse{}
	mi := &file_chat_chat_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageResponse) ProtoMessage() {}

func (x *SendChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageResponse.ProtoReflect.Descriptor instead.
func (*SendChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{16}
}

func (x *SendChatMessageResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendChatMessageResponse) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *SendChatMessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendChatMessageResponse) GetRecentMessages() []*RecentMessage {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

var File_chat_chat_service_proto protoreflect.FileDescriptor

const file_chat_chat_service_proto_rawDesc = "" +
	"\n" +
	"\x17chat/chat_service.proto\x12\x04chat\x1a\x0fchat/chat.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\x12\x1b\n" +
	"\tprompt_id\x18\x02 \x01(\tR\bpromptId\"D\n" +
	"\x15CreateSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.chat.ChatSessionR\asession\"4\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\"E\n" +
	"\x14ListSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.chat.ChatSessionR\bsessions\"<\n" +
	"\x14RenameSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"D\n" +
	"\x15RenameSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.chat.ChatSessionR\asession\"&\n" +
	"\x14DeleteSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x14CreateMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"D\n" +
	"\x15CreateMessageResponse\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.chat.ChatMessageR\amessage\"4\n" +
	"\x13ListMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x14ListMessagesResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.chat.ChatMessageR\bmessages\"&\n" +
	"\x14DeleteMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8d\x01\n" +
	"\x16SendChatMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x02 \x01(\tR\tvisitorId\x12\x1b\n" +
	"\tprompt_id\x18\x03 \x01(\tR\bpromptId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"x\n" +
	"\rRecentMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaf\x01\n" +
	"\x17SendChatMessageResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x02 \x01(\tR\tvisitorId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12<\n" +
	"\x0frecent_messages\x18\x04 \x03(\v2\x13.chat.RecentMessageR\x0erecentMessages2\xdd\x04\n" +
	"\vChatService\x12H\n" +
	"\rCreateSession\x12\x1a.chat.CreateSessionRequest\x1a\x1b.chat.CreateSessionResponse\x12E\n" +
	"\fListSessions\x12\x19.chat.ListSessionsRequest\x1a\x1a.chat.ListSessionsResponse\x12H\n" +
	"\rRenameSession\x12\x1a.chat.RenameSessionRequest\x1a\x1b.chat.RenameSessionResponse\x12H\n" +
	"\rDeleteSession\x12\x1a.chat.DeleteSessionRequest\x1a\x1b.chat.DeleteSessionResponse\x12H\n" +
	"\rCreateMessage\x12\x1a.chat.CreateMessageRequest\x1a\x1b.chat.CreateMessageResponse\x12E\n" +
	"\fListMessages\x12\x19.chat.ListMessagesRequest\x1a\x1a.chat.ListMessagesResponse\x12H\n" +
	"\rDeleteMessage\x12\x1a.chat.DeleteMessageRequest\x1a\x1b.chat.DeleteMessageResponse\x12N\n" +
	"\x0fSendChatMessage\x12\x1c.chat.SendChatMessageRequest\x1a\x1d.chat.SendChatMessageResponseB\x19Z\x17portfolio-ai/proto/chatb\x06proto3"

var (
	file_chat_chat_service_proto_rawDescOnce sync.Once
	file_chat_chat_service_proto_rawDescData []byte
)

func file_chat_chat_service_proto_rawDescGZIP() []byte {
	file_chat_chat_service_proto_rawDescOnce.Do(func() {
		file_chat_chat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_service_proto_rawDesc), len(file_chat_chat_service_proto_rawDesc)))
	})
	return file_chat_chat_service_proto_rawDescData
}

var file_chat_chat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_chat_chat_service_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),    // 0: chat.CreateSessionRequest
	(*CreateSessionResponse)(nil),   // 1: chat.CreateSessionResponse
	(*ListSessionsRequest)(nil),     // 2: chat.ListSessionsRequest
	(*ListSessionsResponse)(nil),    // 3: chat.ListSessionsResponse
	(*RenameSessionRequest)(nil),    // 4: chat.RenameSessionRequest
	(*RenameSessionResponse)(nil),   // 5: chat.RenameSessionResponse
	(*DeleteSessionRequest)(nil),    // 6: chat.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),   // 7: chat.DeleteSessionResponse
	(*CreateMessageRequest)(nil),    // 8: chat.CreateMessageRequest
	(*CreateMessageResponse)(nil),   // 9: chat.CreateMessageResponse
	(*ListMessagesRequest)(nil),     // 10: chat.ListMessagesRequest
	(*ListMessagesResponse)(nil),    // 11: chat.ListMessagesResponse
	(*DeleteMessageRequest)(nil),    // 12: chat.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),   // 13: chat.DeleteMessageResponse
	(*SendChatMessageRequest)(nil),  // 14: chat.SendChatMessageRequest
	(*RecentMessage)(nil),           // 15: chat.RecentMessage
	(*SendChatMessageResponse)(nil), // 16: chat.SendChatMessageResponse
	(*ChatSession)(nil),             // 17: chat.ChatSession
	(*ChatMessage)(nil),             // 18: chat.ChatMessage
	(*timestamppb.Timestamp)(nil),   // 19: google.protobuf.Timestamp
}
var file_chat_chat_service_proto_depIdxs = []int32{
	17, // 0: chat.CreateSessionResponse.session:type_name -> chat.ChatSession
	17, // 1: chat.ListSessionsResponse.sessions:type_name -> chat.ChatSession
	17, // 2: chat.RenameSessionResponse.session:type_name -> chat.ChatSession
	18, // 3: chat.CreateMessageResponse.message:type_name -> chat.ChatMessage
	18, // 4: chat.ListMessagesResponse.messages:type_name -> chat.ChatMessage
	19, // 5: chat.RecentMessage.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: chat.SendChatMessageResponse.recent_messages:type_name -> chat.RecentMessage
	0,  // 7: chat.ChatService.CreateSession:input_type -> chat.CreateSessionRequest
	2,  // 8: chat.ChatService.ListSessions:input_type -> chat.ListSessionsRequest
	4,  // 9: chat.ChatService.RenameSession:input_type -> chat.RenameSessionRequest
	6,  // 10: chat.ChatService.DeleteSession:input_type -> chat.DeleteSessionRequest
	8,  // 11: chat.ChatService.CreateMessage:input_type -> chat.CreateMessageRequest
	10, // 12: chat.ChatService.ListMessages:input_type -> chat.ListMessagesRequest
	12, // 13: chat.ChatService.DeleteMessage:input_type -> chat.DeleteMessageRequest
	14, // 14: chat.ChatService.SendChatMessage:input_type -> chat.SendChatMessageRequest
	1,  // 15: chat.ChatService.CreateSession:output_type -> chat.CreateSessionResponse
	3,  // 16: chat.ChatService.ListSessions:output_type -> chat.ListSessionsResponse
	5,  // 17: chat.ChatService.RenameSession:output_type -> chat.RenameSessionResponse
	7,  // 18: chat.ChatService.DeleteSession:output_type -> chat.DeleteSessionResponse
	9,  // 19: chat.ChatService.CreateMessage:output_type -> chat.CreateMessageResponse
	11, // 20: chat.ChatService.ListMessages:output_type -> chat.ListMessagesResponse
	13, // 21: chat.ChatService.DeleteMessage:output_type -> chat.DeleteMessageResponse
	16, // 22: chat.ChatService.SendChatMessage:output_type -> chat.SendChatMessageResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chat_chat_service_proto_init() }
func file_chat_chat_service_proto_init() {
	if File_chat_chat_service_proto != nil {
		return
	}
	file_chat_chat_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_service_proto_rawDesc), len(file_chat_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chat_service_proto_goTypes,
		DependencyIndexes: file_chat_chat_service_proto_depIdxs,
		MessageInfos:      file_chat_chat_service_proto_msgTypes,
	}.Build()
	File_chat_chat_service_proto = out.File
	file_chat_chat_service_proto_goTypes = nil
	file_chat_chat_service_proto_depIdxs = nil
}
