// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: knowledge/knowledge.proto

package knowledge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KnowledgeDocument struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceType     string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // e.g., "profile", "project", "experience", "certificate", "skill"
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Checksum       string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Version        int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "Pending", "Embedding", "Embedded", "Failed"
	EmbeddingModel string                 `protobuf:"bytes,9,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	LastEmbeddedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_embedded_at,json=lastEmbeddedAt,proto3" json:"last_embedded_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnowledgeDocument) Reset() {
	*x = KnowledgeDocument{}
	mi := &file_knowledge_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeDocument) ProtoMessage() {}

func (x *KnowledgeDocument) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeDocument.ProtoReflect.Descriptor instead.
func (*KnowledgeDocument) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeDocument) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *KnowledgeDocument) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *KnowledgeDocument) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeDocument) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeDocument) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *KnowledgeDocument) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KnowledgeDocument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KnowledgeDocument) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *KnowledgeDocument) GetLastEmbeddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastEmbeddedAt
	}
	return nil
}

func (x *KnowledgeDocument) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeDocument) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type KnowledgeChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId     string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChunkIndex     int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	TokenCount     int32                  `protobuf:"varint,5,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	EmbeddingModel string                 `protobuf:"bytes,6,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnowledgeChunk) Reset() {
	*x = KnowledgeChunk{}
	mi := &file_knowledge_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeChunk) ProtoMessage() {}

func (x *KnowledgeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeChunk.ProtoReflect.Descriptor instead.
func (*KnowledgeChunk) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *KnowledgeChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *KnowledgeChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *KnowledgeChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeChunk) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *KnowledgeChunk) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *KnowledgeChunk) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request and Response for CRUD
type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_knowledge_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_knowledge_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *ListDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDocumentsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*KnowledgeDocument   `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_knowledge_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *ListDocumentsResponse) GetDocuments() []*KnowledgeDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunksRequest) Reset() {
	*x = ListChunksRequest{}
	mi := &file_knowledge_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunksRequest) ProtoMessage() {}

func (x *ListChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunksRequest.ProtoReflect.Descriptor instead.
func (*ListChunksRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *ListChunksRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ListChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*KnowledgeChunk      `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunksResponse) Reset() {
	*x = ListChunksResponse{}
	mi := &file_knowledge_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunksResponse) ProtoMessage() {}

func (x *ListChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunksResponse.ProtoReflect.Descriptor instead.
func (*ListChunksResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *ListChunksResponse) GetChunks() []*KnowledgeChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_knowledge_knowledge_proto protoreflect.FileDescriptor

const file_knowledge_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x19knowledge/knowledge.proto\x12\x16portfolio.knowledge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc4\x03\n" +
	"\x11KnowledgeDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12'\n" +
	"\x0fembedding_model\x18\t \x01(\tR\x0eembeddingModel\x12D\n" +
	"\x10last_embedded_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0elastEmbeddedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x81\x02\n" +
	"\x0eKnowledgeChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vtoken_count\x18\x05 \x01(\x05R\n" +
	"tokenCount\x12'\n" +
	"\x0fembedding_model\x18\x06 \x01(\tR\x0eembeddingModel\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x14ListDocumentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\"\x81\x01\n" +
	"\x15ListDocumentsResponse\x12G\n" +
	"\tdocuments\x18\x01 \x03(\v2).portfolio.knowledge.v1.KnowledgeDocumentR\tdocuments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"4\n" +
	"\x11ListChunksRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"T\n" +
	"\x12ListChunksResponse\x12>\n" +
	"\x06chunks\x18\x01 \x03(\v2&.portfolio.knowledge.v1.KnowledgeChunkR\x06chunks2\xcb\x02\n" +
	"\x10KnowledgeService\x12d\n" +
	"\vGetDocument\x12*.portfolio.knowledge.v1.GetDocumentRequest\x1a).portfolio.knowledge.v1.KnowledgeDocument\x12l\n" +
	"\rListDocuments\x12,.portfolio.knowledge.v1.ListDocumentsRequest\x1a-.portfolio.knowledge.v1.ListDocumentsResponse\x12c\n" +
	"\n" +
	"ListChunks\x12).portfolio.knowledge.v1.ListChunksRequest\x1a*.portfolio.knowledge.v1.ListChunksResponseB\x18Z\x16dan-ai/proto/knowledgeb\x06proto3"

var (
	file_knowledge_knowledge_proto_rawDescOnce sync.Once
	file_knowledge_knowledge_proto_rawDescData []byte
)

func file_knowledge_knowledge_proto_rawDescGZIP() []byte {
	file_knowledge_knowledge_proto_rawDescOnce.Do(func() {
		file_knowledge_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledge_knowledge_proto_rawDesc), len(file_knowledge_knowledge_proto_rawDesc)))
	})
	return file_knowledge_knowledge_proto_rawDescData
}

var file_knowledge_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_knowledge_knowledge_proto_goTypes = []any{
	(*KnowledgeDocument)(nil),     // 0: portfolio.knowledge.v1.KnowledgeDocument
	(*KnowledgeChunk)(nil),        // 1: portfolio.knowledge.v1.KnowledgeChunk
	(*GetDocumentRequest)(nil),    // 2: portfolio.knowledge.v1.GetDocumentRequest
	(*ListDocumentsRequest)(nil),  // 3: portfolio.knowledge.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil), // 4: portfolio.knowledge.v1.ListDocumentsResponse
	(*ListChunksRequest)(nil),     // 5: portfolio.knowledge.v1.ListChunksRequest
	(*ListChunksResponse)(nil),    // 6: portfolio.knowledge.v1.ListChunksResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_knowledge_knowledge_proto_depIdxs = []int32{
	7, // 0: portfolio.knowledge.v1.KnowledgeDocument.last_embedded_at:type_name -> google.protobuf.Timestamp
	7, // 1: portfolio.knowledge.v1.KnowledgeDocument.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: portfolio.knowledge.v1.KnowledgeDocument.updated_at:type_name -> google.protobuf.Timestamp
	7, // 3: portfolio.knowledge.v1.KnowledgeChunk.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: portfolio.knowledge.v1.ListDocumentsResponse.documents:type_name -> portfolio.knowledge.v1.KnowledgeDocument
	1, // 5: portfolio.knowledge.v1.ListChunksResponse.chunks:type_name -> portfolio.knowledge.v1.KnowledgeChunk
	2, // 6: portfolio.knowledge.v1.KnowledgeService.GetDocument:input_type -> portfolio.knowledge.v1.GetDocumentRequest
	3, // 7: portfolio.knowledge.v1.KnowledgeService.ListDocuments:input_type -> portfolio.knowledge.v1.ListDocumentsRequest
	5, // 8: portfolio.knowledge.v1.KnowledgeService.ListChunks:input_type -> portfolio.knowledge.v1.ListChunksRequest
	0, // 9: portfolio.knowledge.v1.KnowledgeService.GetDocument:output_type -> portfolio.knowledge.v1.KnowledgeDocument
	4, // 10: portfolio.knowledge.v1.KnowledgeService.ListDocuments:output_type -> portfolio.knowledge.v1.ListDocumentsResponse
	6, // 11: portfolio.knowledge.v1.KnowledgeService.ListChunks:output_type -> portfolio.knowledge.v1.ListChunksResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_knowledge_knowledge_proto_init() }
func file_knowledge_knowledge_proto_init() {
	if File_knowledge_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledge_knowledge_proto_rawDesc), len(file_knowledge_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledge_knowledge_proto_goTypes,
		DependencyIndexes: file_knowledge_knowledge_proto_depIdxs,
		MessageInfos:      file_knowledge_knowledge_proto_msgTypes,
	}.Build()
	File_knowledge_knowledge_proto = out.File
	file_knowledge_knowledge_proto_goTypes = nil
	file_knowledge_knowledge_proto_depIdxs = nil
}
