// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aimodel/aimodel_service.proto

package aimodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAIModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Temperature    float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ContextWindow  int32                  `protobuf:"varint,5,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	SupportsTools  bool                   `protobuf:"varint,6,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"`
	SupportsStream bool                   `protobuf:"varint,7,opt,name=supports_stream,json=supportsStream,proto3" json:"supports_stream,omitempty"`
	Enabled        bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAIModelRequest) Reset() {
	*x = CreateAIModelRequest{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAIModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIModelRequest) ProtoMessage() {}

func (x *CreateAIModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIModelRequest.ProtoReflect.Descriptor instead.
func (*CreateAIModelRequest) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAIModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAIModelRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateAIModelRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CreateAIModelRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CreateAIModelRequest) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *CreateAIModelRequest) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

func (x *CreateAIModelRequest) GetSupportsStream() bool {
	if x != nil {
		return x.SupportsStream
	}
	return false
}

func (x *CreateAIModelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateAIModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiModel       *AIModel               `protobuf:"bytes,1,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAIModelResponse) Reset() {
	*x = CreateAIModelResponse{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAIModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIModelResponse) ProtoMessage() {}

func (x *CreateAIModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIModelResponse.ProtoReflect.Descriptor instead.
func (*CreateAIModelResponse) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAIModelResponse) GetAiModel() *AIModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

type GetAIModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIModelRequest) Reset() {
	*x = GetAIModelRequest{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIModelRequest) ProtoMessage() {}

func (x *GetAIModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIModelRequest.ProtoReflect.Descriptor instead.
func (*GetAIModelRequest) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAIModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAIModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiModel       *AIModel               `protobuf:"bytes,1,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIModelResponse) Reset() {
	*x = GetAIModelResponse{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIModelResponse) ProtoMessage() {}

func (x *GetAIModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIModelResponse.ProtoReflect.Descriptor instead.
func (*GetAIModelResponse) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAIModelResponse) GetAiModel() *AIModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

type ListAIModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnabledOnly   bool                   `protobuf:"varint,1,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIModelsRequest) Reset() {
	*x = ListAIModelsRequest{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIModelsRequest) ProtoMessage() {}

func (x *ListAIModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIModelsRequest.ProtoReflect.Descriptor instead.
func (*ListAIModelsRequest) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAIModelsRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListAIModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiModels      []*AIModel             `protobuf:"bytes,1,rep,name=ai_models,json=aiModels,proto3" json:"ai_models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIModelsResponse) Reset() {
	*x = ListAIModelsResponse{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIModelsResponse) ProtoMessage() {}

func (x *ListAIModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIModelsResponse.ProtoReflect.Descriptor instead.
func (*ListAIModelsResponse) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAIModelsResponse) GetAiModels() []*AIModel {
	if x != nil {
		return x.AiModels
	}
	return nil
}

type UpdateAIModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Temperature    float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ContextWindow  int32                  `protobuf:"varint,6,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	SupportsTools  bool                   `protobuf:"varint,7,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"`
	SupportsStream bool                   `protobuf:"varint,8,opt,name=supports_stream,json=supportsStream,proto3" json:"supports_stream,omitempty"`
	Enabled        bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAIModelRequest) Reset() {
	*x = UpdateAIModelRequest{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAIModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAIModelRequest) ProtoMessage() {}

func (x *UpdateAIModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAIModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateAIModelRequest) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAIModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAIModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAIModelRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UpdateAIModelRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *UpdateAIModelRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *UpdateAIModelRequest) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *UpdateAIModelRequest) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

func (x *UpdateAIModelRequest) GetSupportsStream() bool {
	if x != nil {
		return x.SupportsStream
	}
	return false
}

func (x *UpdateAIModelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateAIModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiModel       *AIModel               `protobuf:"bytes,1,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAIModelResponse) Reset() {
	*x = UpdateAIModelResponse{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAIModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAIModelResponse) ProtoMessage() {}

func (x *UpdateAIModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAIModelResponse.ProtoReflect.Descriptor instead.
func (*UpdateAIModelResponse) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAIModelResponse) GetAiModel() *AIModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

type DeleteAIModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAIModelRequest) Reset() {
	*x = DeleteAIModelRequest{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAIModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAIModelRequest) ProtoMessage() {}

func (x *DeleteAIModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAIModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteAIModelRequest) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAIModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAIModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAIModelResponse) Reset() {
	*x = DeleteAIModelResponse{}
	mi := &file_aimodel_aimodel_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAIModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAIModelResponse) ProtoMessage() {}

func (x *DeleteAIModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAIModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteAIModelResponse) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAIModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_aimodel_aimodel_service_proto protoreflect.FileDescriptor

const file_aimodel_aimodel_service_proto_rawDesc = "" +
	"\n" +
	"\x1daimodel/aimodel_service.proto\x12\aaimodel\x1a\x15aimodel/aimodel.proto\"\x98\x02\n" +
	"\x14CreateAIModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0econtext_window\x18\x05 \x01(\x05R\rcontextWindow\x12%\n" +
	"\x0esupports_tools\x18\x06 \x01(\bR\rsupportsTools\x12'\n" +
	"\x0fsupports_stream\x18\a \x01(\bR\x0esupportsStream\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"D\n" +
	"\x15CreateAIModelResponse\x12+\n" +
	"\bai_model\x18\x01 \x01(\v2\x10.aimodel.AIModelR\aaiModel\"#\n" +
	"\x11GetAIModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x12GetAIModelResponse\x12+\n" +
	"\bai_model\x18\x01 \x01(\v2\x10.aimodel.AIModelR\aaiModel\"8\n" +
	"\x13ListAIModelsRequest\x12!\n" +
	"\fenabled_only\x18\x01 \x01(\bR\venabledOnly\"E\n" +
	"\x14ListAIModelsResponse\x12-\n" +
	"\tai_models\x18\x01 \x03(\v2\x10.aimodel.AIModelR\baiModels\"\xa8\x02\n" +
	"\x14UpdateAIModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0econtext_window\x18\x06 \x01(\x05R\rcontextWindow\x12%\n" +
	"\x0esupports_tools\x18\a \x01(\bR\rsupportsTools\x12'\n" +
	"\x0fsupports_stream\x18\b \x01(\bR\x0esupportsStream\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"D\n" +
	"\x15UpdateAIModelResponse\x12+\n" +
	"\bai_model\x18\x01 \x01(\v2\x10.aimodel.AIModelR\aaiModel\"&\n" +
	"\x14DeleteAIModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteAIModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x94\x03\n" +
	"\x0eAIModelService\x12N\n" +
	"\rCreateAIModel\x12\x1d.aimodel.CreateAIModelRequest\x1a\x1e.aimodel.CreateAIModelResponse\x12E\n" +
	"\n" +
	"GetAIModel\x12\x1a.aimodel.GetAIModelRequest\x1a\x1b.aimodel.GetAIModelResponse\x12K\n" +
	"\fListAIModels\x12\x1c.aimodel.ListAIModelsRequest\x1a\x1d.aimodel.ListAIModelsResponse\x12N\n" +
	"\rUpdateAIModel\x12\x1d.aimodel.UpdateAIModelRequest\x1a\x1e.aimodel.UpdateAIModelResponse\x12N\n" +
	"\rDeleteAIModel\x12\x1d.aimodel.DeleteAIModelRequest\x1a\x1e.aimodel.DeleteAIModelResponseB\x1cZ\x1aportfolio-ai/proto/aimodelb\x06proto3"

var (
	file_aimodel_aimodel_service_proto_rawDescOnce sync.Once
	file_aimodel_aimodel_service_proto_rawDescData []byte
)

func file_aimodel_aimodel_service_proto_rawDescGZIP() []byte {
	file_aimodel_aimodel_service_proto_rawDescOnce.Do(func() {
		file_aimodel_aimodel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aimodel_aimodel_service_proto_rawDesc), len(file_aimodel_aimodel_service_proto_rawDesc)))
	})
	return file_aimodel_aimodel_service_proto_rawDescData
}

var file_aimodel_aimodel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aimodel_aimodel_service_proto_goTypes = []any{
	(*CreateAIModelRequest)(nil),  // 0: aimodel.CreateAIModelRequest
	(*CreateAIModelResponse)(nil), // 1: aimodel.CreateAIModelResponse
	(*GetAIModelRequest)(nil),     // 2: aimodel.GetAIModelRequest
	(*GetAIModelResponse)(nil),    // 3: aimodel.GetAIModelResponse
	(*ListAIModelsRequest)(nil),   // 4: aimodel.ListAIModelsRequest
	(*ListAIModelsResponse)(nil),  // 5: aimodel.ListAIModelsResponse
	(*UpdateAIModelRequest)(nil),  // 6: aimodel.UpdateAIModelRequest
	(*UpdateAIModelResponse)(nil), // 7: aimodel.UpdateAIModelResponse
	(*DeleteAIModelRequest)(nil),  // 8: aimodel.DeleteAIModelRequest
	(*DeleteAIModelResponse)(nil), // 9: aimodel.DeleteAIModelResponse
	(*AIModel)(nil),               // 10: aimodel.AIModel
}
var file_aimodel_aimodel_service_proto_depIdxs = []int32{
	10, // 0: aimodel.CreateAIModelResponse.ai_model:type_name -> aimodel.AIModel
	10, // 1: aimodel.GetAIModelResponse.ai_model:type_name -> aimodel.AIModel
	10, // 2: aimodel.ListAIModelsResponse.ai_models:type_name -> aimodel.AIModel
	10, // 3: aimodel.UpdateAIModelResponse.ai_model:type_name -> aimodel.AIModel
	0,  // 4: aimodel.AIModelService.CreateAIModel:input_type -> aimodel.CreateAIModelRequest
	2,  // 5: aimodel.AIModelService.GetAIModel:input_type -> aimodel.GetAIModelRequest
	4,  // 6: aimodel.AIModelService.ListAIModels:input_type -> aimodel.ListAIModelsRequest
	6,  // 7: aimodel.AIModelService.UpdateAIModel:input_type -> aimodel.UpdateAIModelRequest
	8,  // 8: aimodel.AIModelService.DeleteAIModel:input_type -> aimodel.DeleteAIModelRequest
	1,  // 9: aimodel.AIModelService.CreateAIModel:output_type -> aimodel.CreateAIModelResponse
	3,  // 10: aimodel.AIModelService.GetAIModel:output_type -> aimodel.GetAIModelResponse
	5,  // 11: aimodel.AIModelService.ListAIModels:output_type -> aimodel.ListAIModelsResponse
	7,  // 12: aimodel.AIModelService.UpdateAIModel:output_type -> aimodel.UpdateAIModelResponse
	9,  // 13: aimodel.AIModelService.DeleteAIModel:output_type -> aimodel.DeleteAIModelResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_aimodel_aimodel_service_proto_init() }
func file_aimodel_aimodel_service_proto_init() {
	if File_aimodel_aimodel_service_proto != nil {
		return
	}
	file_aimodel_aimodel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aimodel_aimodel_service_proto_rawDesc), len(file_aimodel_aimodel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aimodel_aimodel_service_proto_goTypes,
		DependencyIndexes: file_aimodel_aimodel_service_proto_depIdxs,
		MessageInfos:      file_aimodel_aimodel_service_proto_msgTypes,
	}.Build()
	File_aimodel_aimodel_service_proto = out.File
	file_aimodel_aimodel_service_proto_goTypes = nil
	file_aimodel_aimodel_service_proto_depIdxs = nil
}
