// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aimodel/aimodel.proto

package aimodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AIModel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Temperature    float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ContextWindow  int32                  `protobuf:"varint,6,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	SupportsTools  bool                   `protobuf:"varint,7,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"`
	SupportsStream bool                   `protobuf:"varint,8,opt,name=supports_stream,json=supportsStream,proto3" json:"supports_stream,omitempty"`
	Enabled        bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AIModel) Reset() {
	*x = AIModel{}
	mi := &file_aimodel_aimodel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIModel) ProtoMessage() {}

func (x *AIModel) ProtoReflect() protoreflect.Message {
	mi := &file_aimodel_aimodel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIModel.ProtoReflect.Descriptor instead.
func (*AIModel) Descriptor() ([]byte, []int) {
	return file_aimodel_aimodel_proto_rawDescGZIP(), []int{0}
}

func (x *AIModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AIModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AIModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIModel) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AIModel) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *AIModel) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *AIModel) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

func (x *AIModel) GetSupportsStream() bool {
	if x != nil {
		return x.SupportsStream
	}
	return false
}

func (x *AIModel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_aimodel_aimodel_proto protoreflect.FileDescriptor

const file_aimodel_aimodel_proto_rawDesc = "" +
	"\n" +
	"\x15aimodel/aimodel.proto\x12\aaimodel\"\x9b\x02\n" +
	"\aAIModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0econtext_window\x18\x06 \x01(\x05R\rcontextWindow\x12%\n" +
	"\x0esupports_tools\x18\a \x01(\bR\rsupportsTools\x12'\n" +
	"\x0fsupports_stream\x18\b \x01(\bR\x0esupportsStream\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabledB\x1cZ\x1aportfolio-ai/proto/aimodelb\x06proto3"

var (
	file_aimodel_aimodel_proto_rawDescOnce sync.Once
	file_aimodel_aimodel_proto_rawDescData []byte
)

func file_aimodel_aimodel_proto_rawDescGZIP() []byte {
	file_aimodel_aimodel_proto_rawDescOnce.Do(func() {
		file_aimodel_aimodel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aimodel_aimodel_proto_rawDesc), len(file_aimodel_aimodel_proto_rawDesc)))
	})
	return file_aimodel_aimodel_proto_rawDescData
}

var file_aimodel_aimodel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aimodel_aimodel_proto_goTypes = []any{
	(*AIModel)(nil), // 0: aimodel.AIModel
}
var file_aimodel_aimodel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aimodel_aimodel_proto_init() }
func file_aimodel_aimodel_proto_init() {
	if File_aimodel_aimodel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aimodel_aimodel_proto_rawDesc), len(file_aimodel_aimodel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aimodel_aimodel_proto_goTypes,
		DependencyIndexes: file_aimodel_aimodel_proto_depIdxs,
		MessageInfos:      file_aimodel_aimodel_proto_msgTypes,
	}.Build()
	File_aimodel_aimodel_proto = out.File
	file_aimodel_aimodel_proto_goTypes = nil
	file_aimodel_aimodel_proto_depIdxs = nil
}
