// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: aimodel/aimodel_service.proto

package aimodel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIModelService_CreateAIModel_FullMethodName = "/aimodel.AIModelService/CreateAIModel"
	AIModelService_GetAIModel_FullMethodName    = "/aimodel.AIModelService/GetAIModel"
	AIModelService_ListAIModels_FullMethodName  = "/aimodel.AIModelService/ListAIModels"
	AIModelService_UpdateAIModel_FullMethodName = "/aimodel.AIModelService/UpdateAIModel"
	AIModelService_DeleteAIModel_FullMethodName = "/aimodel.AIModelService/DeleteAIModel"
)

// AIModelServiceClient is the client API for AIModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIModelServiceClient interface {
	CreateAIModel(ctx context.Context, in *CreateAIModelRequest, opts ...grpc.CallOption) (*CreateAIModelResponse, error)
	GetAIModel(ctx context.Context, in *GetAIModelRequest, opts ...grpc.CallOption) (*GetAIModelResponse, error)
	ListAIModels(ctx context.Context, in *ListAIModelsRequest, opts ...grpc.CallOption) (*ListAIModelsResponse, error)
	UpdateAIModel(ctx context.Context, in *UpdateAIModelRequest, opts ...grpc.CallOption) (*UpdateAIModelResponse, error)
	DeleteAIModel(ctx context.Context, in *DeleteAIModelRequest, opts ...grpc.CallOption) (*DeleteAIModelResponse, error)
}

type aIModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIModelServiceClient(cc grpc.ClientConnInterface) AIModelServiceClient {
	return &aIModelServiceClient{cc}
}

func (c *aIModelServiceClient) CreateAIModel(ctx context.Context, in *CreateAIModelRequest, opts ...grpc.CallOption) (*CreateAIModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAIModelResponse)
	err := c.cc.Invoke(ctx, AIModelService_CreateAIModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) GetAIModel(ctx context.Context, in *GetAIModelRequest, opts ...grpc.CallOption) (*GetAIModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAIModelResponse)
	err := c.cc.Invoke(ctx, AIModelService_GetAIModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) ListAIModels(ctx context.Context, in *ListAIModelsRequest, opts ...grpc.CallOption) (*ListAIModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAIModelsResponse)
	err := c.cc.Invoke(ctx, AIModelService_ListAIModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) UpdateAIModel(ctx context.Context, in *UpdateAIModelRequest, opts ...grpc.CallOption) (*UpdateAIModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAIModelResponse)
	err := c.cc.Invoke(ctx, AIModelService_UpdateAIModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelServiceClient) DeleteAIModel(ctx context.Context, in *DeleteAIModelRequest, opts ...grpc.CallOption) (*DeleteAIModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAIModelResponse)
	err := c.cc.Invoke(ctx, AIModelService_DeleteAIModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIModelServiceServer is the server API for AIModelService service.
// All implementations must embed UnimplementedAIModelServiceServer
// for forward compatibility.
type AIModelServiceServer interface {
	CreateAIModel(context.Context, *CreateAIModelRequest) (*CreateAIModelResponse, error)
	GetAIModel(context.Context, *GetAIModelRequest) (*GetAIModelResponse, error)
	ListAIModels(context.Context, *ListAIModelsRequest) (*ListAIModelsResponse, error)
	UpdateAIModel(context.Context, *UpdateAIModelRequest) (*UpdateAIModelResponse, error)
	DeleteAIModel(context.Context, *DeleteAIModelRequest) (*DeleteAIModelResponse, error)
	mustEmbedUnimplementedAIModelServiceServer()
}

// UnimplementedAIModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIModelServiceServer struct{}

func (UnimplementedAIModelServiceServer) CreateAIModel(context.Context, *CreateAIModelRequest) (*CreateAIModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAIModel not implemented")
}
func (UnimplementedAIModelServiceServer) GetAIModel(context.Context, *GetAIModelRequest) (*GetAIModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAIModel not implemented")
}
func (UnimplementedAIModelServiceServer) ListAIModels(context.Context, *ListAIModelsRequest) (*ListAIModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAIModels not implemented")
}
func (UnimplementedAIModelServiceServer) UpdateAIModel(context.Context, *UpdateAIModelRequest) (*UpdateAIModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAIModel not implemented")
}
func (UnimplementedAIModelServiceServer) DeleteAIModel(context.Context, *DeleteAIModelRequest) (*DeleteAIModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAIModel not implemented")
}
func (UnimplementedAIModelServiceServer) mustEmbedUnimplementedAIModelServiceServer() {}
func (UnimplementedAIModelServiceServer) testEmbeddedByValue()                        {}

// UnsafeAIModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIModelServiceServer will
// result in compilation errors.
type UnsafeAIModelServiceServer interface {
	mustEmbedUnimplementedAIModelServiceServer()
}

func RegisterAIModelServiceServer(s grpc.ServiceRegistrar, srv AIModelServiceServer) {
	// If the following call panics, it indicates UnimplementedAIModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIModelService_ServiceDesc, srv)
}

func _AIModelService_CreateAIModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAIModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).CreateAIModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_CreateAIModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).CreateAIModel(ctx, req.(*CreateAIModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_GetAIModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).GetAIModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_GetAIModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).GetAIModel(ctx, req.(*GetAIModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_ListAIModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).ListAIModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_ListAIModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).ListAIModels(ctx, req.(*ListAIModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_UpdateAIModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAIModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).UpdateAIModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_UpdateAIModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).UpdateAIModel(ctx, req.(*UpdateAIModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModelService_DeleteAIModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAIModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelServiceServer).DeleteAIModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModelService_DeleteAIModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelServiceServer).DeleteAIModel(ctx, req.(*DeleteAIModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIModelService_ServiceDesc is the grpc.ServiceDesc for AIModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aimodel.AIModelService",
	HandlerType: (*AIModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAIModel",
			Handler:    _AIModelService_CreateAIModel_Handler,
		},
		{
			MethodName: "GetAIModel",
			Handler:    _AIModelService_GetAIModel_Handler,
		},
		{
			MethodName: "ListAIModels",
			Handler:    _AIModelService_ListAIModels_Handler,
		},
		{
			MethodName: "UpdateAIModel",
			Handler:    _AIModelService_UpdateAIModel_Handler,
		},
		{
			MethodName: "DeleteAIModel",
			Handler:    _AIModelService_DeleteAIModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aimodel/aimodel_service.proto",
}
