// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package visitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VisitorServiceClient is the client API for VisitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisitorServiceClient interface {
	RegisterVisitor(ctx context.Context, in *RegisterVisitorRequest, opts ...grpc.CallOption) (*RegisterVisitorResponse, error)
	GetVisitor(ctx context.Context, in *GetVisitorRequest, opts ...grpc.CallOption) (*GetVisitorResponse, error)
}

type visitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisitorServiceClient(cc grpc.ClientConnInterface) VisitorServiceClient {
	return &visitorServiceClient{cc}
}

func (c *visitorServiceClient) RegisterVisitor(ctx context.Context, in *RegisterVisitorRequest, opts ...grpc.CallOption) (*RegisterVisitorResponse, error) {
	out := new(RegisterVisitorResponse)
	err := c.cc.Invoke(ctx, "/visitor.VisitorService/RegisterVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visitorServiceClient) GetVisitor(ctx context.Context, in *GetVisitorRequest, opts ...grpc.CallOption) (*GetVisitorResponse, error) {
	out := new(GetVisitorResponse)
	err := c.cc.Invoke(ctx, "/visitor.VisitorService/GetVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisitorServiceServer is the server API for VisitorService service.
// All implementations must embed UnimplementedVisitorServiceServer
// for forward compatibility
type VisitorServiceServer interface {
	RegisterVisitor(context.Context, *RegisterVisitorRequest) (*RegisterVisitorResponse, error)
	GetVisitor(context.Context, *GetVisitorRequest) (*GetVisitorResponse, error)
	mustEmbedUnimplementedVisitorServiceServer()
}

// UnimplementedVisitorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVisitorServiceServer struct {
}

func (UnimplementedVisitorServiceServer) RegisterVisitor(context.Context, *RegisterVisitorRequest) (*RegisterVisitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVisitor not implemented")
}
func (UnimplementedVisitorServiceServer) GetVisitor(context.Context, *GetVisitorRequest) (*GetVisitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitor not implemented")
}
func (UnimplementedVisitorServiceServer) mustEmbedUnimplementedVisitorServiceServer() {}

// UnsafeVisitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisitorServiceServer will
// result in compilation errors.
type UnsafeVisitorServiceServer interface {
	mustEmbedUnimplementedVisitorServiceServer()
}

func RegisterVisitorServiceServer(s grpc.ServiceRegistrar, srv VisitorServiceServer) {
	s.RegisterService(&VisitorService_ServiceDesc, srv)
}

func _VisitorService_RegisterVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVisitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitorServiceServer).RegisterVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visitor.VisitorService/RegisterVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitorServiceServer).RegisterVisitor(ctx, req.(*RegisterVisitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisitorService_GetVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVisitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitorServiceServer).GetVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visitor.VisitorService/GetVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitorServiceServer).GetVisitor(ctx, req.(*GetVisitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisitorService_ServiceDesc is the grpc.ServiceDesc for VisitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "visitor.VisitorService",
	HandlerType: (*VisitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVisitor",
			Handler:    _VisitorService_RegisterVisitor_Handler,
		},
		{
			MethodName: "GetVisitor",
			Handler:    _VisitorService_GetVisitor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "visitor/visitor_service.proto",
}
