// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: visitor/visitor_service.proto

package visitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterVisitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorId     string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVisitorRequest) Reset() {
	*x = RegisterVisitorRequest{}
	mi := &file_visitor_visitor_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVisitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVisitorRequest) ProtoMessage() {}

func (x *RegisterVisitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_visitor_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVisitorRequest.ProtoReflect.Descriptor instead.
func (*RegisterVisitorRequest) Descriptor() ([]byte, []int) {
	return file_visitor_visitor_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterVisitorRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

type RegisterVisitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visitor       *Visitor               `protobuf:"bytes,1,opt,name=visitor,proto3" json:"visitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVisitorResponse) Reset() {
	*x = RegisterVisitorResponse{}
	mi := &file_visitor_visitor_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVisitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVisitorResponse) ProtoMessage() {}

func (x *RegisterVisitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_visitor_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVisitorResponse.ProtoReflect.Descriptor instead.
func (*RegisterVisitorResponse) Descriptor() ([]byte, []int) {
	return file_visitor_visitor_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterVisitorResponse) GetVisitor() *Visitor {
	if x != nil {
		return x.Visitor
	}
	return nil
}

type GetVisitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVisitorRequest) Reset() {
	*x = GetVisitorRequest{}
	mi := &file_visitor_visitor_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVisitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitorRequest) ProtoMessage() {}

func (x *GetVisitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_visitor_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitorRequest.ProtoReflect.Descriptor instead.
func (*GetVisitorRequest) Descriptor() ([]byte, []int) {
	return file_visitor_visitor_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetVisitorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVisitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visitor       *Visitor               `protobuf:"bytes,1,opt,name=visitor,proto3" json:"visitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVisitorResponse) Reset() {
	*x = GetVisitorResponse{}
	mi := &file_visitor_visitor_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVisitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitorResponse) ProtoMessage() {}

func (x *GetVisitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_visitor_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitorResponse.ProtoReflect.Descriptor instead.
func (*GetVisitorResponse) Descriptor() ([]byte, []int) {
	return file_visitor_visitor_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetVisitorResponse) GetVisitor() *Visitor {
	if x != nil {
		return x.Visitor
	}
	return nil
}

var File_visitor_visitor_service_proto protoreflect.FileDescriptor

const file_visitor_visitor_service_proto_rawDesc = "" +
	"\n" +
	"\x1dvisitor/visitor_service.proto\x12\avisitor\x1a\x15visitor/visitor.proto\"7\n" +
	"\x16RegisterVisitorRequest\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\"E\n" +
	"\x17RegisterVisitorResponse\x12*\n" +
	"\avisitor\x18\x01 \x01(\v2\x10.visitor.VisitorR\avisitor\"#\n" +
	"\x11GetVisitorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetVisitorResponse\x12*\n" +
	"\avisitor\x18\x01 \x01(\v2\x10.visitor.VisitorR\avisitor2\xad\x01\n" +
	"\x0eVisitorService\x12T\n" +
	"\x0fRegisterVisitor\x12\x1f.visitor.RegisterVisitorRequest\x1a .visitor.RegisterVisitorResponse\x12E\n" +
	"\n" +
	"GetVisitor\x12\x1a.visitor.GetVisitorRequest\x1a\x1b.visitor.GetVisitorResponseB\x1cZ\x1aportfolio-ai/proto/visitorb\x06proto3"

var (
	file_visitor_visitor_service_proto_rawDescOnce sync.Once
	file_visitor_visitor_service_proto_rawDescData []byte
)

func file_visitor_visitor_service_proto_rawDescGZIP() []byte {
	file_visitor_visitor_service_proto_rawDescOnce.Do(func() {
		file_visitor_visitor_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visitor_visitor_service_proto_rawDesc), len(file_visitor_visitor_service_proto_rawDesc)))
	})
	return file_visitor_visitor_service_proto_rawDescData
}

var file_visitor_visitor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_visitor_visitor_service_proto_goTypes = []any{
	(*RegisterVisitorRequest)(nil),  // 0: visitor.RegisterVisitorRequest
	(*RegisterVisitorResponse)(nil), // 1: visitor.RegisterVisitorResponse
	(*GetVisitorRequest)(nil),       // 2: visitor.GetVisitorRequest
	(*GetVisitorResponse)(nil),      // 3: visitor.GetVisitorResponse
	(*Visitor)(nil),                 // 4: visitor.Visitor
}
var file_visitor_visitor_service_proto_depIdxs = []int32{
	4, // 0: visitor.RegisterVisitorResponse.visitor:type_name -> visitor.Visitor
	4, // 1: visitor.GetVisitorResponse.visitor:type_name -> visitor.Visitor
	0, // 2: visitor.VisitorService.RegisterVisitor:input_type -> visitor.RegisterVisitorRequest
	2, // 3: visitor.VisitorService.GetVisitor:input_type -> visitor.GetVisitorRequest
	1, // 4: visitor.VisitorService.RegisterVisitor:output_type -> visitor.RegisterVisitorResponse
	3, // 5: visitor.VisitorService.GetVisitor:output_type -> visitor.GetVisitorResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_visitor_visitor_service_proto_init() }
func file_visitor_visitor_service_proto_init() {
	if File_visitor_visitor_service_proto != nil {
		return
	}
	file_visitor_visitor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visitor_visitor_service_proto_rawDesc), len(file_visitor_visitor_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_visitor_visitor_service_proto_goTypes,
		DependencyIndexes: file_visitor_visitor_service_proto_depIdxs,
		MessageInfos:      file_visitor_visitor_service_proto_msgTypes,
	}.Build()
	File_visitor_visitor_service_proto = out.File
	file_visitor_visitor_service_proto_goTypes = nil
	file_visitor_visitor_service_proto_depIdxs = nil
}
