// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: visitor/visitor.proto

package visitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visitor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstSeenAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	TotalMessages int32                  `protobuf:"varint,4,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Visitor) Reset() {
	*x = Visitor{}
	mi := &file_visitor_visitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Visitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visitor) ProtoMessage() {}

func (x *Visitor) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_visitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visitor.ProtoReflect.Descriptor instead.
func (*Visitor) Descriptor() ([]byte, []int) {
	return file_visitor_visitor_proto_rawDescGZIP(), []int{0}
}

func (x *Visitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Visitor) GetFirstSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenAt
	}
	return nil
}

func (x *Visitor) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Visitor) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *Visitor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Visitor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_visitor_visitor_proto protoreflect.FileDescriptor

const file_visitor_visitor_proto_rawDesc = "" +
	"\n" +
	"\x15visitor/visitor.proto\x12\avisitor\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n" +
	"\aVisitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\rfirst_seen_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vfirstSeenAt\x12<\n" +
	"\flast_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12%\n" +
	"\x0etotal_messages\x18\x04 \x01(\x05R\rtotalMessages\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x1cZ\x1aportfolio-ai/proto/visitorb\x06proto3"

var (
	file_visitor_visitor_proto_rawDescOnce sync.Once
	file_visitor_visitor_proto_rawDescData []byte
)

func file_visitor_visitor_proto_rawDescGZIP() []byte {
	file_visitor_visitor_proto_rawDescOnce.Do(func() {
		file_visitor_visitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visitor_visitor_proto_rawDesc), len(file_visitor_visitor_proto_rawDesc)))
	})
	return file_visitor_visitor_proto_rawDescData
}

var file_visitor_visitor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_visitor_visitor_proto_goTypes = []any{
	(*Visitor)(nil),               // 0: visitor.Visitor
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_visitor_visitor_proto_depIdxs = []int32{
	1, // 0: visitor.Visitor.first_seen_at:type_name -> google.protobuf.Timestamp
	1, // 1: visitor.Visitor.last_seen_at:type_name -> google.protobuf.Timestamp
	1, // 2: visitor.Visitor.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: visitor.Visitor.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_visitor_visitor_proto_init() }
func file_visitor_visitor_proto_init() {
	if File_visitor_visitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visitor_visitor_proto_rawDesc), len(file_visitor_visitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_visitor_visitor_proto_goTypes,
		DependencyIndexes: file_visitor_visitor_proto_depIdxs,
		MessageInfos:      file_visitor_visitor_proto_msgTypes,
	}.Build()
	File_visitor_visitor_proto = out.File
	file_visitor_visitor_proto_goTypes = nil
	file_visitor_visitor_proto_depIdxs = nil
}
