// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package experience

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExperienceServiceClient is the client API for ExperienceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExperienceServiceClient interface {
	ListExperiences(ctx context.Context, in *ListExperiencesRequest, opts ...grpc.CallOption) (*ListExperiencesResponse, error)
	GetExperience(ctx context.Context, in *GetExperienceRequest, opts ...grpc.CallOption) (*GetExperienceResponse, error)
	CreateExperience(ctx context.Context, in *CreateExperienceRequest, opts ...grpc.CallOption) (*CreateExperienceResponse, error)
	UpdateExperience(ctx context.Context, in *UpdateExperienceRequest, opts ...grpc.CallOption) (*UpdateExperienceResponse, error)
	DeleteExperience(ctx context.Context, in *DeleteExperienceRequest, opts ...grpc.CallOption) (*DeleteExperienceResponse, error)
}

type experienceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExperienceServiceClient(cc grpc.ClientConnInterface) ExperienceServiceClient {
	return &experienceServiceClient{cc}
}

func (c *experienceServiceClient) ListExperiences(ctx context.Context, in *ListExperiencesRequest, opts ...grpc.CallOption) (*ListExperiencesResponse, error) {
	out := new(ListExperiencesResponse)
	err := c.cc.Invoke(ctx, "/experience.ExperienceService/ListExperiences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) GetExperience(ctx context.Context, in *GetExperienceRequest, opts ...grpc.CallOption) (*GetExperienceResponse, error) {
	out := new(GetExperienceResponse)
	err := c.cc.Invoke(ctx, "/experience.ExperienceService/GetExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) CreateExperience(ctx context.Context, in *CreateExperienceRequest, opts ...grpc.CallOption) (*CreateExperienceResponse, error) {
	out := new(CreateExperienceResponse)
	err := c.cc.Invoke(ctx, "/experience.ExperienceService/CreateExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) UpdateExperience(ctx context.Context, in *UpdateExperienceRequest, opts ...grpc.CallOption) (*UpdateExperienceResponse, error) {
	out := new(UpdateExperienceResponse)
	err := c.cc.Invoke(ctx, "/experience.ExperienceService/UpdateExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) DeleteExperience(ctx context.Context, in *DeleteExperienceRequest, opts ...grpc.CallOption) (*DeleteExperienceResponse, error) {
	out := new(DeleteExperienceResponse)
	err := c.cc.Invoke(ctx, "/experience.ExperienceService/DeleteExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExperienceServiceServer is the server API for ExperienceService service.
// All implementations must embed UnimplementedExperienceServiceServer
// for forward compatibility
type ExperienceServiceServer interface {
	ListExperiences(context.Context, *ListExperiencesRequest) (*ListExperiencesResponse, error)
	GetExperience(context.Context, *GetExperienceRequest) (*GetExperienceResponse, error)
	CreateExperience(context.Context, *CreateExperienceRequest) (*CreateExperienceResponse, error)
	UpdateExperience(context.Context, *UpdateExperienceRequest) (*UpdateExperienceResponse, error)
	DeleteExperience(context.Context, *DeleteExperienceRequest) (*DeleteExperienceResponse, error)
	mustEmbedUnimplementedExperienceServiceServer()
}

// UnimplementedExperienceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExperienceServiceServer struct {
}

func (UnimplementedExperienceServiceServer) ListExperiences(context.Context, *ListExperiencesRequest) (*ListExperiencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExperiences not implemented")
}
func (UnimplementedExperienceServiceServer) GetExperience(context.Context, *GetExperienceRequest) (*GetExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExperience not implemented")
}
func (UnimplementedExperienceServiceServer) CreateExperience(context.Context, *CreateExperienceRequest) (*CreateExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExperience not implemented")
}
func (UnimplementedExperienceServiceServer) UpdateExperience(context.Context, *UpdateExperienceRequest) (*UpdateExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExperience not implemented")
}
func (UnimplementedExperienceServiceServer) DeleteExperience(context.Context, *DeleteExperienceRequest) (*DeleteExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExperience not implemented")
}
func (UnimplementedExperienceServiceServer) mustEmbedUnimplementedExperienceServiceServer() {}

// UnsafeExperienceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExperienceServiceServer will
// result in compilation errors.
type UnsafeExperienceServiceServer interface {
	mustEmbedUnimplementedExperienceServiceServer()
}

func RegisterExperienceServiceServer(s grpc.ServiceRegistrar, srv ExperienceServiceServer) {
	s.RegisterService(&ExperienceService_ServiceDesc, srv)
}

func _ExperienceService_ListExperiences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExperiencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).ListExperiences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/experience.ExperienceService/ListExperiences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).ListExperiences(ctx, req.(*ListExperiencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_GetExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).GetExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/experience.ExperienceService/GetExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).GetExperience(ctx, req.(*GetExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_CreateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).CreateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/experience.ExperienceService/CreateExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).CreateExperience(ctx, req.(*CreateExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_UpdateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).UpdateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/experience.ExperienceService/UpdateExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).UpdateExperience(ctx, req.(*UpdateExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_DeleteExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).DeleteExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/experience.ExperienceService/DeleteExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).DeleteExperience(ctx, req.(*DeleteExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExperienceService_ServiceDesc is the grpc.ServiceDesc for ExperienceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExperienceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "experience.ExperienceService",
	HandlerType: (*ExperienceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListExperiences",
			Handler:    _ExperienceService_ListExperiences_Handler,
		},
		{
			MethodName: "GetExperience",
			Handler:    _ExperienceService_GetExperience_Handler,
		},
		{
			MethodName: "CreateExperience",
			Handler:    _ExperienceService_CreateExperience_Handler,
		},
		{
			MethodName: "UpdateExperience",
			Handler:    _ExperienceService_UpdateExperience_Handler,
		},
		{
			MethodName: "DeleteExperience",
			Handler:    _ExperienceService_DeleteExperience_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "experience/experience_service.proto",
}
